// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package test

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_HOME PhoneType = 0
	PhoneType_WORK PhoneType = 1
)

var PhoneType_name = map[int32]string{
	0: "HOME",
	1: "WORK",
}

var PhoneType_value = map[string]int32{
	"HOME": 0,
	"WORK": 1,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

type DataReq struct {
	Request              string   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataReq) Reset()         { *m = DataReq{} }
func (m *DataReq) String() string { return proto.CompactTextString(m) }
func (*DataReq) ProtoMessage()    {}
func (*DataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *DataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataReq.Unmarshal(m, b)
}
func (m *DataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataReq.Marshal(b, m, deterministic)
}
func (m *DataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataReq.Merge(m, src)
}
func (m *DataReq) XXX_Size() int {
	return xxx_messageInfo_DataReq.Size(m)
}
func (m *DataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DataReq.DiscardUnknown(m)
}

var xxx_messageInfo_DataReq proto.InternalMessageInfo

func (m *DataReq) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

type DataRep struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRep) Reset()         { *m = DataRep{} }
func (m *DataRep) String() string { return proto.CompactTextString(m) }
func (*DataRep) ProtoMessage()    {}
func (*DataRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *DataRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRep.Unmarshal(m, b)
}
func (m *DataRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRep.Marshal(b, m, deterministic)
}
func (m *DataRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRep.Merge(m, src)
}
func (m *DataRep) XXX_Size() int {
	return xxx_messageInfo_DataRep.Size(m)
}
func (m *DataRep) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRep.DiscardUnknown(m)
}

var xxx_messageInfo_DataRep proto.InternalMessageInfo

func (m *DataRep) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type Phone struct {
	Type                 PhoneType `protobuf:"varint,1,opt,name=type,proto3,enum=test.PhoneType" json:"type,omitempty"`
	Number               string    `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Phone) Reset()         { *m = Phone{} }
func (m *Phone) String() string { return proto.CompactTextString(m) }
func (*Phone) ProtoMessage()    {}
func (*Phone) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *Phone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phone.Unmarshal(m, b)
}
func (m *Phone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phone.Marshal(b, m, deterministic)
}
func (m *Phone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phone.Merge(m, src)
}
func (m *Phone) XXX_Size() int {
	return xxx_messageInfo_Phone.Size(m)
}
func (m *Phone) XXX_DiscardUnknown() {
	xxx_messageInfo_Phone.DiscardUnknown(m)
}

var xxx_messageInfo_Phone proto.InternalMessageInfo

func (m *Phone) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_HOME
}

func (m *Phone) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type Person struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phones               []*Phone `protobuf:"bytes,3,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetPhones() []*Phone {
	if m != nil {
		return m.Phones
	}
	return nil
}

type ContactBook struct {
	Persons              []*Person `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ContactBook) Reset()         { *m = ContactBook{} }
func (m *ContactBook) String() string { return proto.CompactTextString(m) }
func (*ContactBook) ProtoMessage()    {}
func (*ContactBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *ContactBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactBook.Unmarshal(m, b)
}
func (m *ContactBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactBook.Marshal(b, m, deterministic)
}
func (m *ContactBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactBook.Merge(m, src)
}
func (m *ContactBook) XXX_Size() int {
	return xxx_messageInfo_ContactBook.Size(m)
}
func (m *ContactBook) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactBook.DiscardUnknown(m)
}

var xxx_messageInfo_ContactBook proto.InternalMessageInfo

func (m *ContactBook) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

func init() {
	proto.RegisterEnum("test.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*DataReq)(nil), "test.DataReq")
	proto.RegisterType((*DataRep)(nil), "test.DataRep")
	proto.RegisterType((*Phone)(nil), "test.Phone")
	proto.RegisterType((*Person)(nil), "test.Person")
	proto.RegisterType((*ContactBook)(nil), "test.ContactBook")
}

func init() {
	proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e)
}

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xcf, 0x6b, 0xc2, 0x30,
	0x14, 0xb6, 0xb5, 0xb6, 0xf6, 0x75, 0x73, 0xf2, 0x0e, 0xa3, 0x78, 0x99, 0xa4, 0x6c, 0x94, 0x1d,
	0x3c, 0x74, 0xf8, 0x0f, 0x4c, 0x07, 0xc2, 0x18, 0x76, 0x61, 0xb0, 0x73, 0x5d, 0x1f, 0x4c, 0x36,
	0x93, 0xd8, 0xc4, 0x83, 0xff, 0xfd, 0x68, 0x4c, 0x65, 0xde, 0xbe, 0x2f, 0xdf, 0xaf, 0x90, 0x00,
	0x18, 0xd2, 0x66, 0xa6, 0x1a, 0x69, 0x24, 0x06, 0x2d, 0x66, 0x19, 0x44, 0xcb, 0xca, 0x54, 0x9c,
	0xf6, 0x98, 0x42, 0xd4, 0xd0, 0xfe, 0x40, 0xda, 0xa4, 0xde, 0xd4, 0xcb, 0x63, 0xde, 0x51, 0x76,
	0xdf, 0x99, 0x14, 0x4e, 0x60, 0xd8, 0x90, 0x56, 0x52, 0x68, 0x72, 0xae, 0x33, 0x67, 0x4b, 0x18,
	0x94, 0xdf, 0x52, 0x10, 0x66, 0x10, 0x98, 0xa3, 0x3a, 0x19, 0x46, 0xc5, 0xcd, 0xcc, 0xae, 0x5a,
	0xe9, 0xe3, 0xa8, 0x88, 0x5b, 0x11, 0x6f, 0x21, 0x14, 0x87, 0xdd, 0x86, 0x9a, 0xd4, 0xb7, 0x3d,
	0x8e, 0xb1, 0x77, 0x08, 0x4b, 0x6a, 0xb4, 0x14, 0x38, 0x02, 0x7f, 0x5b, 0xdb, 0x92, 0x01, 0xf7,
	0xb7, 0x35, 0x22, 0x04, 0xa2, 0xda, 0x91, 0xf3, 0x5b, 0x8c, 0x19, 0x84, 0xaa, 0x2d, 0xd6, 0x69,
	0x7f, 0xda, 0xcf, 0x93, 0x22, 0xf9, 0x37, 0xc6, 0x9d, 0xc4, 0xe6, 0x90, 0x2c, 0xa4, 0x30, 0xd5,
	0x97, 0x79, 0x96, 0xf2, 0x07, 0x1f, 0x20, 0x52, 0x76, 0x41, 0xa7, 0x9e, 0x0d, 0x5d, 0xb9, 0x90,
	0x3d, 0xe4, 0x9d, 0xf8, 0x78, 0x07, 0xf1, 0xf9, 0xd2, 0x38, 0x84, 0x60, 0xb5, 0x7e, 0x7b, 0x19,
	0xf7, 0x5a, 0xf4, 0xb9, 0xe6, 0xaf, 0x63, 0xaf, 0x98, 0x43, 0xcc, 0xcb, 0xc5, 0xaa, 0x12, 0xf5,
	0x2f, 0x61, 0x0e, 0xa1, 0x43, 0xd7, 0xa7, 0x3a, 0xf7, 0xae, 0x93, 0x0b, 0xaa, 0x58, 0x6f, 0x13,
	0xda, 0x0f, 0x78, 0xfa, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x06, 0x8d, 0x98, 0x8e, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RPCHandleClient is the client API for RPCHandle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCHandleClient interface {
	Handle(ctx context.Context, in *DataReq, opts ...grpc.CallOption) (*DataRep, error)
}

type rPCHandleClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCHandleClient(cc grpc.ClientConnInterface) RPCHandleClient {
	return &rPCHandleClient{cc}
}

func (c *rPCHandleClient) Handle(ctx context.Context, in *DataReq, opts ...grpc.CallOption) (*DataRep, error) {
	out := new(DataRep)
	err := c.cc.Invoke(ctx, "/test.RPCHandle/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCHandleServer is the server API for RPCHandle service.
type RPCHandleServer interface {
	Handle(context.Context, *DataReq) (*DataRep, error)
}

// UnimplementedRPCHandleServer can be embedded to have forward compatible implementations.
type UnimplementedRPCHandleServer struct {
}

func (*UnimplementedRPCHandleServer) Handle(ctx context.Context, req *DataReq) (*DataRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}

func RegisterRPCHandleServer(s *grpc.Server, srv RPCHandleServer) {
	s.RegisterService(&_RPCHandle_serviceDesc, srv)
}

func _RPCHandle_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCHandleServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.RPCHandle/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCHandleServer).Handle(ctx, req.(*DataReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCHandle_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.RPCHandle",
	HandlerType: (*RPCHandleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _RPCHandle_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
